config/routes.rb
Rails.application.routes.draw do
  root to: 'show#welcome'
  get '/welcome', to: 'show#welcome'
  get '/event', to: 'show#event'
  get '/matches', to: 'show#matches'
  get '/wrestlers', to: 'roster#wrestlers'
  get '/championships', to: 'roster#championships'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/roster_controller.rb
class RosterController < ApplicationController

  def wrestlers
    @wrestlerlist = ['Bobby', 'Robert', 'James', 'Randy', 'Steve', 'Mark']
  end

  def champions
    
  end

end

app/controllers/show_controller.rb
class ShowController < ApplicationController

  def welcome

  end

  def event

  end

  def matches

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WrestlingFed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>My wrestling fed</h1>
<nav>
<%= link_to "Home", welcome_path %>
<%= link_to "Event", event_path %>
<%= link_to "Matches", matches_path %>
<%= link_to "Wrestlers", wrestlers_path %>
<%= link_to "Championships", championships_path %>
</nav>
<%= yield %>

</body>
</html>

app/views/roster/championships.html.erb
<h2>List of our Titles</h2>
<p>What they're all fighting for</p>

<%= image_tag('http://www.wildcatbelts.com/images/Wrestling/UCW/ucw-60.jpg')%>

app/views/roster/wrestlers.html.erb
<h2>List of Wrestlers</h2>
<p>Our terrifying roster</p>
<ul>
<% @wrestlerlist.each do |wrestler| %>
<li><%= wrestler.capitalize %></li>
<% end %></ul>

app/views/show/event.html.erb
<p>Our next show is in <%= distance_of_time_in_words(Time.now, Time.now + 3.days) %></p>

app/views/show/matches.html.erb
<p>Who would you like to see fight?</p>

<%= form_tag(matches_path, method: :get) do %>
  <p>Enter a search term below</p>
  <%= text_field_tag :wrestler1 %> vs <%= text_field_tag :wrestler2 %>
  <%= submit_tag "go" %>
<% end %>

<%= "You said #{params['wrestler1']} vs #{params['wrestler2']}" if params['wrestler1'] %>

app/views/show/welcome.html.erb
Welcome to our Wrestling Federation